CREATE TABLE "mytable" (
  "-- Task 4: SQL for Data Analysis (E-commerce dataset)" text
);

INSERT INTO "mytable" ("-- Task 4: SQL for Data Analysis (E-commerce dataset)")
VALUES
('-- Created by: Siva Sakthi R'),
('-- Date: 26/10/25'),
('-- 1️⃣ Create tables'),
('CREATE TABLE customers ('),
('customer_id INTEGER PRIMARY KEY'),
('name TEXT'),
('country TEXT'),
(');'),
('CREATE TABLE orders ('),
('order_id INTEGER PRIMARY KEY'),
('customer_id INTEGER'),
('product TEXT'),
('quantity INTEGER'),
('price REAL'),
('order_date TEXT'),
(');'),
('-- 2️⃣ Insert sample data'),
('INSERT INTO customers VALUES'),
('(1'),
('(2'),
('(3'),
('INSERT INTO orders VALUES'),
('(101'),
('(102'),
('(103'),
('(104'),
('-- 3️⃣ Queries'),
('SELECT * FROM orders;'),
('SELECT * FROM orders WHERE price > 100;'),
('SELECT customer_id'),
('FROM orders GROUP BY customer_id ORDER BY total_spent DESC;'),
('SELECT c.name'),
('FROM customers c JOIN orders o ON c.customer_id = o.customer_id;'),
('SELECT AVG(price*quantity) AS avg_order_value FROM orders;'),
('-- 4️⃣ View + index'),
('CREATE VIEW customer_summary AS'),
('SELECT c.name'),
('FROM customers c JOIN orders o ON c.customer_id=o.customer_id'),
('GROUP BY c.name;'),
('SELECT * FROM customer_summary;'),
('CREATE INDEX idx_orders_customer ON orders(customer_id);');
